port: 3000

gui_user: true
gui_graphql: false

db_name: 'sqlite.db'
db_force: ''

fetcher_sleep: 1000
fetcher_interval: 600000
fetcher_timeout: 10000
fetcher_agent: 'rss-parser'

tuners_default:
  - name: 'sanitizer'
    z: 40
  - name: 'minifier'
    z: 80

import_upload_max_filesize: 500000