PORT: 3000

GUI_USER: true
GUI_GRAPHQL: false

DB_NAME: 'sqlite.db'
DB_FORCE: ''
DB_CACHED: true

FETCHER_INTERVAL: 30000
FETCHER_TIMEOUT: 10000
FETCHER_AGENT: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36'
