#!/bin/bash

query='
mutation( $m: FeedsFilterInput! ) {
    Sync( o: $m ) {
        feeds {
            date
            feed_id
        }
    }
}'

cases=(
    '{
        "flr_limit": 5
    }'
)

for i in "${cases[@]}"
do
    variables="{ \"m\": $i}"
    source .run
done