#!/bin/bash

query='
mutation( $m: SyncData! ) {
    Sync( o: $m ) {
        feeds {
            date
        }
    }
}'

cases=(
    '{
        "limit": 5
    }'
)

for i in "${cases[@]}"
do
    variables="{ \"m\": $i}"
    source .run
done