name: Docker Image CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: docker/setup-qemu-action@v1
    - uses: docker/setup-buildx-action@v1
    - uses: docker/login-action@v1
      with:
        username: gllera
        password: ${{ secrets.TOKEN }}
    - name: Build the Docker image
      run: docker buildx build --platform linux/amd64,linux/arm64 --tag gllera/rsss --output "type=image,push=true" .
